/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTestImport } from './routes/_layout/test'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutResearchReportsWeeklyInsightsReportsImport } from './routes/_layout/research-reports.weekly-insights-reports'
import { Route as LayoutResearchReportsSpecialReportsImport } from './routes/_layout/research-reports.special-reports'
import { Route as LayoutResearchReportsMutualFundReportsImport } from './routes/_layout/research-reports.mutual-fund-reports'
import { Route as LayoutResearchReportsMonthlyInsightsReportsImport } from './routes/_layout/research-reports.monthly-insights-reports'
import { Route as LayoutResearchReportsFundamentalReportsImport } from './routes/_layout/research-reports.fundamental-reports'
import { Route as LayoutResearchReportsDailyInsightsReportsImport } from './routes/_layout/research-reports.daily-insights-reports'
import { Route as LayoutResearchReportsCommodityCurrencyReportsImport } from './routes/_layout/research-reports.commodity-currency-reports'
import { Route as LayoutAcclReportsPoliciesImport } from './routes/_layout/accl-reports.policies'
import { Route as LayoutAcclReportsInvestorRelationDocumentsImport } from './routes/_layout/accl-reports.investor-relation-documents'
import { Route as LayoutAcclReportsFamilirizationProgrammieImport } from './routes/_layout/accl-reports.familirization-programmie'
import { Route as LayoutAcclReportsAnnualReportsImport } from './routes/_layout/accl-reports.annual-reports'
import { Route as LayoutResearchReportsWeeklyInsightReportsAddImport } from './routes/_layout/research-reports.weekly-insight-reports.add'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestRoute = LayoutTestImport.update({
  path: '/test',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResearchReportsWeeklyInsightsReportsRoute =
  LayoutResearchReportsWeeklyInsightsReportsImport.update({
    path: '/research-reports/weekly-insights-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsSpecialReportsRoute =
  LayoutResearchReportsSpecialReportsImport.update({
    path: '/research-reports/special-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMutualFundReportsRoute =
  LayoutResearchReportsMutualFundReportsImport.update({
    path: '/research-reports/mutual-fund-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMonthlyInsightsReportsRoute =
  LayoutResearchReportsMonthlyInsightsReportsImport.update({
    path: '/research-reports/monthly-insights-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsFundamentalReportsRoute =
  LayoutResearchReportsFundamentalReportsImport.update({
    path: '/research-reports/fundamental-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsDailyInsightsReportsRoute =
  LayoutResearchReportsDailyInsightsReportsImport.update({
    path: '/research-reports/daily-insights-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsCommodityCurrencyReportsRoute =
  LayoutResearchReportsCommodityCurrencyReportsImport.update({
    path: '/research-reports/commodity-currency-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclReportsPoliciesRoute = LayoutAcclReportsPoliciesImport.update({
  path: '/accl-reports/policies',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAcclReportsInvestorRelationDocumentsRoute =
  LayoutAcclReportsInvestorRelationDocumentsImport.update({
    path: '/accl-reports/investor-relation-documents',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclReportsFamilirizationProgrammieRoute =
  LayoutAcclReportsFamilirizationProgrammieImport.update({
    path: '/accl-reports/familirization-programmie',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclReportsAnnualReportsRoute =
  LayoutAcclReportsAnnualReportsImport.update({
    path: '/accl-reports/annual-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsWeeklyInsightReportsAddRoute =
  LayoutResearchReportsWeeklyInsightReportsAddImport.update({
    path: '/research-reports/weekly-insight-reports/add',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/test': {
      id: '/_layout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof LayoutTestImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl-reports/annual-reports': {
      id: '/_layout/accl-reports/annual-reports'
      path: '/accl-reports/annual-reports'
      fullPath: '/accl-reports/annual-reports'
      preLoaderRoute: typeof LayoutAcclReportsAnnualReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl-reports/familirization-programmie': {
      id: '/_layout/accl-reports/familirization-programmie'
      path: '/accl-reports/familirization-programmie'
      fullPath: '/accl-reports/familirization-programmie'
      preLoaderRoute: typeof LayoutAcclReportsFamilirizationProgrammieImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl-reports/investor-relation-documents': {
      id: '/_layout/accl-reports/investor-relation-documents'
      path: '/accl-reports/investor-relation-documents'
      fullPath: '/accl-reports/investor-relation-documents'
      preLoaderRoute: typeof LayoutAcclReportsInvestorRelationDocumentsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl-reports/policies': {
      id: '/_layout/accl-reports/policies'
      path: '/accl-reports/policies'
      fullPath: '/accl-reports/policies'
      preLoaderRoute: typeof LayoutAcclReportsPoliciesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/commodity-currency-reports': {
      id: '/_layout/research-reports/commodity-currency-reports'
      path: '/research-reports/commodity-currency-reports'
      fullPath: '/research-reports/commodity-currency-reports'
      preLoaderRoute: typeof LayoutResearchReportsCommodityCurrencyReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/daily-insights-reports': {
      id: '/_layout/research-reports/daily-insights-reports'
      path: '/research-reports/daily-insights-reports'
      fullPath: '/research-reports/daily-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsDailyInsightsReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/fundamental-reports': {
      id: '/_layout/research-reports/fundamental-reports'
      path: '/research-reports/fundamental-reports'
      fullPath: '/research-reports/fundamental-reports'
      preLoaderRoute: typeof LayoutResearchReportsFundamentalReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/monthly-insights-reports': {
      id: '/_layout/research-reports/monthly-insights-reports'
      path: '/research-reports/monthly-insights-reports'
      fullPath: '/research-reports/monthly-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsMonthlyInsightsReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/mutual-fund-reports': {
      id: '/_layout/research-reports/mutual-fund-reports'
      path: '/research-reports/mutual-fund-reports'
      fullPath: '/research-reports/mutual-fund-reports'
      preLoaderRoute: typeof LayoutResearchReportsMutualFundReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/special-reports': {
      id: '/_layout/research-reports/special-reports'
      path: '/research-reports/special-reports'
      fullPath: '/research-reports/special-reports'
      preLoaderRoute: typeof LayoutResearchReportsSpecialReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/weekly-insights-reports': {
      id: '/_layout/research-reports/weekly-insights-reports'
      path: '/research-reports/weekly-insights-reports'
      fullPath: '/research-reports/weekly-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsWeeklyInsightsReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/weekly-insight-reports/add': {
      id: '/_layout/research-reports/weekly-insight-reports/add'
      path: '/research-reports/weekly-insight-reports/add'
      fullPath: '/research-reports/weekly-insight-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsWeeklyInsightReportsAddImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutTestRoute: typeof LayoutTestRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAcclReportsAnnualReportsRoute: typeof LayoutAcclReportsAnnualReportsRoute
  LayoutAcclReportsFamilirizationProgrammieRoute: typeof LayoutAcclReportsFamilirizationProgrammieRoute
  LayoutAcclReportsInvestorRelationDocumentsRoute: typeof LayoutAcclReportsInvestorRelationDocumentsRoute
  LayoutAcclReportsPoliciesRoute: typeof LayoutAcclReportsPoliciesRoute
  LayoutResearchReportsCommodityCurrencyReportsRoute: typeof LayoutResearchReportsCommodityCurrencyReportsRoute
  LayoutResearchReportsDailyInsightsReportsRoute: typeof LayoutResearchReportsDailyInsightsReportsRoute
  LayoutResearchReportsFundamentalReportsRoute: typeof LayoutResearchReportsFundamentalReportsRoute
  LayoutResearchReportsMonthlyInsightsReportsRoute: typeof LayoutResearchReportsMonthlyInsightsReportsRoute
  LayoutResearchReportsMutualFundReportsRoute: typeof LayoutResearchReportsMutualFundReportsRoute
  LayoutResearchReportsSpecialReportsRoute: typeof LayoutResearchReportsSpecialReportsRoute
  LayoutResearchReportsWeeklyInsightsReportsRoute: typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  LayoutResearchReportsWeeklyInsightReportsAddRoute: typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutTestRoute: LayoutTestRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAcclReportsAnnualReportsRoute: LayoutAcclReportsAnnualReportsRoute,
  LayoutAcclReportsFamilirizationProgrammieRoute:
    LayoutAcclReportsFamilirizationProgrammieRoute,
  LayoutAcclReportsInvestorRelationDocumentsRoute:
    LayoutAcclReportsInvestorRelationDocumentsRoute,
  LayoutAcclReportsPoliciesRoute: LayoutAcclReportsPoliciesRoute,
  LayoutResearchReportsCommodityCurrencyReportsRoute:
    LayoutResearchReportsCommodityCurrencyReportsRoute,
  LayoutResearchReportsDailyInsightsReportsRoute:
    LayoutResearchReportsDailyInsightsReportsRoute,
  LayoutResearchReportsFundamentalReportsRoute:
    LayoutResearchReportsFundamentalReportsRoute,
  LayoutResearchReportsMonthlyInsightsReportsRoute:
    LayoutResearchReportsMonthlyInsightsReportsRoute,
  LayoutResearchReportsMutualFundReportsRoute:
    LayoutResearchReportsMutualFundReportsRoute,
  LayoutResearchReportsSpecialReportsRoute:
    LayoutResearchReportsSpecialReportsRoute,
  LayoutResearchReportsWeeklyInsightsReportsRoute:
    LayoutResearchReportsWeeklyInsightsReportsRoute,
  LayoutResearchReportsWeeklyInsightReportsAddRoute:
    LayoutResearchReportsWeeklyInsightReportsAddRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof LayoutAboutRoute
  '/test': typeof LayoutTestRoute
  '/': typeof LayoutIndexRoute
  '/accl-reports/annual-reports': typeof LayoutAcclReportsAnnualReportsRoute
  '/accl-reports/familirization-programmie': typeof LayoutAcclReportsFamilirizationProgrammieRoute
  '/accl-reports/investor-relation-documents': typeof LayoutAcclReportsInvestorRelationDocumentsRoute
  '/accl-reports/policies': typeof LayoutAcclReportsPoliciesRoute
  '/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsRoute
  '/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsRoute
  '/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsRoute
  '/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsRoute
  '/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsRoute
  '/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsRoute
  '/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  '/research-reports/weekly-insight-reports/add': typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof LayoutAboutRoute
  '/test': typeof LayoutTestRoute
  '/': typeof LayoutIndexRoute
  '/accl-reports/annual-reports': typeof LayoutAcclReportsAnnualReportsRoute
  '/accl-reports/familirization-programmie': typeof LayoutAcclReportsFamilirizationProgrammieRoute
  '/accl-reports/investor-relation-documents': typeof LayoutAcclReportsInvestorRelationDocumentsRoute
  '/accl-reports/policies': typeof LayoutAcclReportsPoliciesRoute
  '/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsRoute
  '/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsRoute
  '/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsRoute
  '/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsRoute
  '/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsRoute
  '/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsRoute
  '/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  '/research-reports/weekly-insight-reports/add': typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/test': typeof LayoutTestRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/accl-reports/annual-reports': typeof LayoutAcclReportsAnnualReportsRoute
  '/_layout/accl-reports/familirization-programmie': typeof LayoutAcclReportsFamilirizationProgrammieRoute
  '/_layout/accl-reports/investor-relation-documents': typeof LayoutAcclReportsInvestorRelationDocumentsRoute
  '/_layout/accl-reports/policies': typeof LayoutAcclReportsPoliciesRoute
  '/_layout/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsRoute
  '/_layout/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsRoute
  '/_layout/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsRoute
  '/_layout/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsRoute
  '/_layout/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsRoute
  '/_layout/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsRoute
  '/_layout/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  '/_layout/research-reports/weekly-insight-reports/add': typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/about'
    | '/test'
    | '/'
    | '/accl-reports/annual-reports'
    | '/accl-reports/familirization-programmie'
    | '/accl-reports/investor-relation-documents'
    | '/accl-reports/policies'
    | '/research-reports/commodity-currency-reports'
    | '/research-reports/daily-insights-reports'
    | '/research-reports/fundamental-reports'
    | '/research-reports/monthly-insights-reports'
    | '/research-reports/mutual-fund-reports'
    | '/research-reports/special-reports'
    | '/research-reports/weekly-insights-reports'
    | '/research-reports/weekly-insight-reports/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/test'
    | '/'
    | '/accl-reports/annual-reports'
    | '/accl-reports/familirization-programmie'
    | '/accl-reports/investor-relation-documents'
    | '/accl-reports/policies'
    | '/research-reports/commodity-currency-reports'
    | '/research-reports/daily-insights-reports'
    | '/research-reports/fundamental-reports'
    | '/research-reports/monthly-insights-reports'
    | '/research-reports/mutual-fund-reports'
    | '/research-reports/special-reports'
    | '/research-reports/weekly-insights-reports'
    | '/research-reports/weekly-insight-reports/add'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/about'
    | '/_layout/test'
    | '/_layout/'
    | '/_layout/accl-reports/annual-reports'
    | '/_layout/accl-reports/familirization-programmie'
    | '/_layout/accl-reports/investor-relation-documents'
    | '/_layout/accl-reports/policies'
    | '/_layout/research-reports/commodity-currency-reports'
    | '/_layout/research-reports/daily-insights-reports'
    | '/_layout/research-reports/fundamental-reports'
    | '/_layout/research-reports/monthly-insights-reports'
    | '/_layout/research-reports/mutual-fund-reports'
    | '/_layout/research-reports/special-reports'
    | '/_layout/research-reports/weekly-insights-reports'
    | '/_layout/research-reports/weekly-insight-reports/add'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/test",
        "/_layout/",
        "/_layout/accl-reports/annual-reports",
        "/_layout/accl-reports/familirization-programmie",
        "/_layout/accl-reports/investor-relation-documents",
        "/_layout/accl-reports/policies",
        "/_layout/research-reports/commodity-currency-reports",
        "/_layout/research-reports/daily-insights-reports",
        "/_layout/research-reports/fundamental-reports",
        "/_layout/research-reports/monthly-insights-reports",
        "/_layout/research-reports/mutual-fund-reports",
        "/_layout/research-reports/special-reports",
        "/_layout/research-reports/weekly-insights-reports",
        "/_layout/research-reports/weekly-insight-reports/add"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/test": {
      "filePath": "_layout/test.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl-reports/annual-reports": {
      "filePath": "_layout/accl-reports.annual-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl-reports/familirization-programmie": {
      "filePath": "_layout/accl-reports.familirization-programmie.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl-reports/investor-relation-documents": {
      "filePath": "_layout/accl-reports.investor-relation-documents.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl-reports/policies": {
      "filePath": "_layout/accl-reports.policies.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/commodity-currency-reports": {
      "filePath": "_layout/research-reports.commodity-currency-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/daily-insights-reports": {
      "filePath": "_layout/research-reports.daily-insights-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/fundamental-reports": {
      "filePath": "_layout/research-reports.fundamental-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/monthly-insights-reports": {
      "filePath": "_layout/research-reports.monthly-insights-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/mutual-fund-reports": {
      "filePath": "_layout/research-reports.mutual-fund-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/special-reports": {
      "filePath": "_layout/research-reports.special-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/weekly-insights-reports": {
      "filePath": "_layout/research-reports.weekly-insights-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/weekly-insight-reports/add": {
      "filePath": "_layout/research-reports.weekly-insight-reports.add.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
