/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutUsersImport } from './routes/_layout/users'
import { Route as LayoutTestImport } from './routes/_layout/test'
import { Route as LayoutMarginUpdatesImport } from './routes/_layout/margin-updates'
import { Route as LayoutFundTransferImport } from './routes/_layout/fund-transfer'
import { Route as LayoutDownloadsImport } from './routes/_layout/downloads'
import { Route as LayoutAddClientImport } from './routes/_layout/add-client'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutResearchReportsWeeklyInsightsReportsImport } from './routes/_layout/research-reports.weekly-insights-reports'
import { Route as LayoutResearchReportsSpecialReportsImport } from './routes/_layout/research-reports.special-reports'
import { Route as LayoutResearchReportsMutualFundReportsImport } from './routes/_layout/research-reports.mutual-fund-reports'
import { Route as LayoutResearchReportsMonthlyInsightsReportsImport } from './routes/_layout/research-reports.monthly-insights-reports'
import { Route as LayoutResearchReportsFundamentalReportsImport } from './routes/_layout/research-reports.fundamental-reports'
import { Route as LayoutResearchReportsDailyInsightsReportsImport } from './routes/_layout/research-reports.daily-insights-reports'
import { Route as LayoutResearchReportsCommodityCurrencyReportsImport } from './routes/_layout/research-reports.commodity-currency-reports'
import { Route as LayoutAcclPoliciesIndexImport } from './routes/_layout/accl/policies/index'
import { Route as LayoutAcclInvestorRelationDocumentsIndexImport } from './routes/_layout/accl/investor-relation-documents/index'
import { Route as LayoutAcclFamiliarizationProgrammeIndexImport } from './routes/_layout/accl/familiarization-programme/index'
import { Route as LayoutAcclAnnualReportsIndexImport } from './routes/_layout/accl/annual-reports/index'
import { Route as LayoutResearchReportsWeeklyInsightReportsAddImport } from './routes/_layout/research-reports.weekly-insight-reports.add'
import { Route as LayoutResearchReportsSpecialReportsAddImport } from './routes/_layout/research-reports.special-reports.add'
import { Route as LayoutResearchReportsMutualFundReportsAddImport } from './routes/_layout/research-reports.mutual-fund-reports.add'
import { Route as LayoutResearchReportsMonthlyInsightsReportsAddImport } from './routes/_layout/research-reports.monthly-insights-reports.add'
import { Route as LayoutResearchReportsFundamentalReportsAddImport } from './routes/_layout/research-reports.fundamental-reports.add'
import { Route as LayoutResearchReportsDailyInsightsReportsAddImport } from './routes/_layout/research-reports.daily-insights-reports.add'
import { Route as LayoutResearchReportsCommodityCurrencyReportsAddImport } from './routes/_layout/research-reports.commodity-currency-reports.add'
import { Route as LayoutAcclPoliciesAddIndexImport } from './routes/_layout/accl/policies/add/index'
import { Route as LayoutAcclInvestorRelationDocumentsAddIndexImport } from './routes/_layout/accl/investor-relation-documents/add/index'
import { Route as LayoutAcclFamiliarizationProgrammeAddIndexImport } from './routes/_layout/accl/familiarization-programme/add/index'
import { Route as LayoutAcclAnnualReportsAddIndexImport } from './routes/_layout/accl/annual-reports/add/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersRoute = LayoutUsersImport.update({
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestRoute = LayoutTestImport.update({
  path: '/test',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMarginUpdatesRoute = LayoutMarginUpdatesImport.update({
  path: '/margin-updates',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFundTransferRoute = LayoutFundTransferImport.update({
  path: '/fund-transfer',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDownloadsRoute = LayoutDownloadsImport.update({
  path: '/downloads',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAddClientRoute = LayoutAddClientImport.update({
  path: '/add-client',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResearchReportsWeeklyInsightsReportsRoute =
  LayoutResearchReportsWeeklyInsightsReportsImport.update({
    path: '/research-reports/weekly-insights-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsSpecialReportsRoute =
  LayoutResearchReportsSpecialReportsImport.update({
    path: '/research-reports/special-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMutualFundReportsRoute =
  LayoutResearchReportsMutualFundReportsImport.update({
    path: '/research-reports/mutual-fund-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMonthlyInsightsReportsRoute =
  LayoutResearchReportsMonthlyInsightsReportsImport.update({
    path: '/research-reports/monthly-insights-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsFundamentalReportsRoute =
  LayoutResearchReportsFundamentalReportsImport.update({
    path: '/research-reports/fundamental-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsDailyInsightsReportsRoute =
  LayoutResearchReportsDailyInsightsReportsImport.update({
    path: '/research-reports/daily-insights-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsCommodityCurrencyReportsRoute =
  LayoutResearchReportsCommodityCurrencyReportsImport.update({
    path: '/research-reports/commodity-currency-reports',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclPoliciesIndexRoute = LayoutAcclPoliciesIndexImport.update({
  path: '/accl/policies/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAcclInvestorRelationDocumentsIndexRoute =
  LayoutAcclInvestorRelationDocumentsIndexImport.update({
    path: '/accl/investor-relation-documents/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclFamiliarizationProgrammeIndexRoute =
  LayoutAcclFamiliarizationProgrammeIndexImport.update({
    path: '/accl/familiarization-programme/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclAnnualReportsIndexRoute =
  LayoutAcclAnnualReportsIndexImport.update({
    path: '/accl/annual-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsWeeklyInsightReportsAddRoute =
  LayoutResearchReportsWeeklyInsightReportsAddImport.update({
    path: '/research-reports/weekly-insight-reports/add',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsSpecialReportsAddRoute =
  LayoutResearchReportsSpecialReportsAddImport.update({
    path: '/add',
    getParentRoute: () => LayoutResearchReportsSpecialReportsRoute,
  } as any)

const LayoutResearchReportsMutualFundReportsAddRoute =
  LayoutResearchReportsMutualFundReportsAddImport.update({
    path: '/add',
    getParentRoute: () => LayoutResearchReportsMutualFundReportsRoute,
  } as any)

const LayoutResearchReportsMonthlyInsightsReportsAddRoute =
  LayoutResearchReportsMonthlyInsightsReportsAddImport.update({
    path: '/add',
    getParentRoute: () => LayoutResearchReportsMonthlyInsightsReportsRoute,
  } as any)

const LayoutResearchReportsFundamentalReportsAddRoute =
  LayoutResearchReportsFundamentalReportsAddImport.update({
    path: '/add',
    getParentRoute: () => LayoutResearchReportsFundamentalReportsRoute,
  } as any)

const LayoutResearchReportsDailyInsightsReportsAddRoute =
  LayoutResearchReportsDailyInsightsReportsAddImport.update({
    path: '/add',
    getParentRoute: () => LayoutResearchReportsDailyInsightsReportsRoute,
  } as any)

const LayoutResearchReportsCommodityCurrencyReportsAddRoute =
  LayoutResearchReportsCommodityCurrencyReportsAddImport.update({
    path: '/add',
    getParentRoute: () => LayoutResearchReportsCommodityCurrencyReportsRoute,
  } as any)

const LayoutAcclPoliciesAddIndexRoute = LayoutAcclPoliciesAddIndexImport.update(
  {
    path: '/accl/policies/add/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutAcclInvestorRelationDocumentsAddIndexRoute =
  LayoutAcclInvestorRelationDocumentsAddIndexImport.update({
    path: '/accl/investor-relation-documents/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclFamiliarizationProgrammeAddIndexRoute =
  LayoutAcclFamiliarizationProgrammeAddIndexImport.update({
    path: '/accl/familiarization-programme/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclAnnualReportsAddIndexRoute =
  LayoutAcclAnnualReportsAddIndexImport.update({
    path: '/accl/annual-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/add-client': {
      id: '/_layout/add-client'
      path: '/add-client'
      fullPath: '/add-client'
      preLoaderRoute: typeof LayoutAddClientImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/downloads': {
      id: '/_layout/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof LayoutDownloadsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/fund-transfer': {
      id: '/_layout/fund-transfer'
      path: '/fund-transfer'
      fullPath: '/fund-transfer'
      preLoaderRoute: typeof LayoutFundTransferImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/margin-updates': {
      id: '/_layout/margin-updates'
      path: '/margin-updates'
      fullPath: '/margin-updates'
      preLoaderRoute: typeof LayoutMarginUpdatesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/test': {
      id: '/_layout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof LayoutTestImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/commodity-currency-reports': {
      id: '/_layout/research-reports/commodity-currency-reports'
      path: '/research-reports/commodity-currency-reports'
      fullPath: '/research-reports/commodity-currency-reports'
      preLoaderRoute: typeof LayoutResearchReportsCommodityCurrencyReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/daily-insights-reports': {
      id: '/_layout/research-reports/daily-insights-reports'
      path: '/research-reports/daily-insights-reports'
      fullPath: '/research-reports/daily-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsDailyInsightsReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/fundamental-reports': {
      id: '/_layout/research-reports/fundamental-reports'
      path: '/research-reports/fundamental-reports'
      fullPath: '/research-reports/fundamental-reports'
      preLoaderRoute: typeof LayoutResearchReportsFundamentalReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/monthly-insights-reports': {
      id: '/_layout/research-reports/monthly-insights-reports'
      path: '/research-reports/monthly-insights-reports'
      fullPath: '/research-reports/monthly-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsMonthlyInsightsReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/mutual-fund-reports': {
      id: '/_layout/research-reports/mutual-fund-reports'
      path: '/research-reports/mutual-fund-reports'
      fullPath: '/research-reports/mutual-fund-reports'
      preLoaderRoute: typeof LayoutResearchReportsMutualFundReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/special-reports': {
      id: '/_layout/research-reports/special-reports'
      path: '/research-reports/special-reports'
      fullPath: '/research-reports/special-reports'
      preLoaderRoute: typeof LayoutResearchReportsSpecialReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/weekly-insights-reports': {
      id: '/_layout/research-reports/weekly-insights-reports'
      path: '/research-reports/weekly-insights-reports'
      fullPath: '/research-reports/weekly-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsWeeklyInsightsReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/commodity-currency-reports/add': {
      id: '/_layout/research-reports/commodity-currency-reports/add'
      path: '/add'
      fullPath: '/research-reports/commodity-currency-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsCommodityCurrencyReportsAddImport
      parentRoute: typeof LayoutResearchReportsCommodityCurrencyReportsImport
    }
    '/_layout/research-reports/daily-insights-reports/add': {
      id: '/_layout/research-reports/daily-insights-reports/add'
      path: '/add'
      fullPath: '/research-reports/daily-insights-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsDailyInsightsReportsAddImport
      parentRoute: typeof LayoutResearchReportsDailyInsightsReportsImport
    }
    '/_layout/research-reports/fundamental-reports/add': {
      id: '/_layout/research-reports/fundamental-reports/add'
      path: '/add'
      fullPath: '/research-reports/fundamental-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsFundamentalReportsAddImport
      parentRoute: typeof LayoutResearchReportsFundamentalReportsImport
    }
    '/_layout/research-reports/monthly-insights-reports/add': {
      id: '/_layout/research-reports/monthly-insights-reports/add'
      path: '/add'
      fullPath: '/research-reports/monthly-insights-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsMonthlyInsightsReportsAddImport
      parentRoute: typeof LayoutResearchReportsMonthlyInsightsReportsImport
    }
    '/_layout/research-reports/mutual-fund-reports/add': {
      id: '/_layout/research-reports/mutual-fund-reports/add'
      path: '/add'
      fullPath: '/research-reports/mutual-fund-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsMutualFundReportsAddImport
      parentRoute: typeof LayoutResearchReportsMutualFundReportsImport
    }
    '/_layout/research-reports/special-reports/add': {
      id: '/_layout/research-reports/special-reports/add'
      path: '/add'
      fullPath: '/research-reports/special-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsSpecialReportsAddImport
      parentRoute: typeof LayoutResearchReportsSpecialReportsImport
    }
    '/_layout/research-reports/weekly-insight-reports/add': {
      id: '/_layout/research-reports/weekly-insight-reports/add'
      path: '/research-reports/weekly-insight-reports/add'
      fullPath: '/research-reports/weekly-insight-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsWeeklyInsightReportsAddImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/annual-reports/': {
      id: '/_layout/accl/annual-reports/'
      path: '/accl/annual-reports'
      fullPath: '/accl/annual-reports'
      preLoaderRoute: typeof LayoutAcclAnnualReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/familiarization-programme/': {
      id: '/_layout/accl/familiarization-programme/'
      path: '/accl/familiarization-programme'
      fullPath: '/accl/familiarization-programme'
      preLoaderRoute: typeof LayoutAcclFamiliarizationProgrammeIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/investor-relation-documents/': {
      id: '/_layout/accl/investor-relation-documents/'
      path: '/accl/investor-relation-documents'
      fullPath: '/accl/investor-relation-documents'
      preLoaderRoute: typeof LayoutAcclInvestorRelationDocumentsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/policies/': {
      id: '/_layout/accl/policies/'
      path: '/accl/policies'
      fullPath: '/accl/policies'
      preLoaderRoute: typeof LayoutAcclPoliciesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/annual-reports/add/': {
      id: '/_layout/accl/annual-reports/add/'
      path: '/accl/annual-reports/add'
      fullPath: '/accl/annual-reports/add'
      preLoaderRoute: typeof LayoutAcclAnnualReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/familiarization-programme/add/': {
      id: '/_layout/accl/familiarization-programme/add/'
      path: '/accl/familiarization-programme/add'
      fullPath: '/accl/familiarization-programme/add'
      preLoaderRoute: typeof LayoutAcclFamiliarizationProgrammeAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/investor-relation-documents/add/': {
      id: '/_layout/accl/investor-relation-documents/add/'
      path: '/accl/investor-relation-documents/add'
      fullPath: '/accl/investor-relation-documents/add'
      preLoaderRoute: typeof LayoutAcclInvestorRelationDocumentsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/policies/add/': {
      id: '/_layout/accl/policies/add/'
      path: '/accl/policies/add'
      fullPath: '/accl/policies/add'
      preLoaderRoute: typeof LayoutAcclPoliciesAddIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutResearchReportsCommodityCurrencyReportsRouteChildren {
  LayoutResearchReportsCommodityCurrencyReportsAddRoute: typeof LayoutResearchReportsCommodityCurrencyReportsAddRoute
}

const LayoutResearchReportsCommodityCurrencyReportsRouteChildren: LayoutResearchReportsCommodityCurrencyReportsRouteChildren =
  {
    LayoutResearchReportsCommodityCurrencyReportsAddRoute:
      LayoutResearchReportsCommodityCurrencyReportsAddRoute,
  }

const LayoutResearchReportsCommodityCurrencyReportsRouteWithChildren =
  LayoutResearchReportsCommodityCurrencyReportsRoute._addFileChildren(
    LayoutResearchReportsCommodityCurrencyReportsRouteChildren,
  )

interface LayoutResearchReportsDailyInsightsReportsRouteChildren {
  LayoutResearchReportsDailyInsightsReportsAddRoute: typeof LayoutResearchReportsDailyInsightsReportsAddRoute
}

const LayoutResearchReportsDailyInsightsReportsRouteChildren: LayoutResearchReportsDailyInsightsReportsRouteChildren =
  {
    LayoutResearchReportsDailyInsightsReportsAddRoute:
      LayoutResearchReportsDailyInsightsReportsAddRoute,
  }

const LayoutResearchReportsDailyInsightsReportsRouteWithChildren =
  LayoutResearchReportsDailyInsightsReportsRoute._addFileChildren(
    LayoutResearchReportsDailyInsightsReportsRouteChildren,
  )

interface LayoutResearchReportsFundamentalReportsRouteChildren {
  LayoutResearchReportsFundamentalReportsAddRoute: typeof LayoutResearchReportsFundamentalReportsAddRoute
}

const LayoutResearchReportsFundamentalReportsRouteChildren: LayoutResearchReportsFundamentalReportsRouteChildren =
  {
    LayoutResearchReportsFundamentalReportsAddRoute:
      LayoutResearchReportsFundamentalReportsAddRoute,
  }

const LayoutResearchReportsFundamentalReportsRouteWithChildren =
  LayoutResearchReportsFundamentalReportsRoute._addFileChildren(
    LayoutResearchReportsFundamentalReportsRouteChildren,
  )

interface LayoutResearchReportsMonthlyInsightsReportsRouteChildren {
  LayoutResearchReportsMonthlyInsightsReportsAddRoute: typeof LayoutResearchReportsMonthlyInsightsReportsAddRoute
}

const LayoutResearchReportsMonthlyInsightsReportsRouteChildren: LayoutResearchReportsMonthlyInsightsReportsRouteChildren =
  {
    LayoutResearchReportsMonthlyInsightsReportsAddRoute:
      LayoutResearchReportsMonthlyInsightsReportsAddRoute,
  }

const LayoutResearchReportsMonthlyInsightsReportsRouteWithChildren =
  LayoutResearchReportsMonthlyInsightsReportsRoute._addFileChildren(
    LayoutResearchReportsMonthlyInsightsReportsRouteChildren,
  )

interface LayoutResearchReportsMutualFundReportsRouteChildren {
  LayoutResearchReportsMutualFundReportsAddRoute: typeof LayoutResearchReportsMutualFundReportsAddRoute
}

const LayoutResearchReportsMutualFundReportsRouteChildren: LayoutResearchReportsMutualFundReportsRouteChildren =
  {
    LayoutResearchReportsMutualFundReportsAddRoute:
      LayoutResearchReportsMutualFundReportsAddRoute,
  }

const LayoutResearchReportsMutualFundReportsRouteWithChildren =
  LayoutResearchReportsMutualFundReportsRoute._addFileChildren(
    LayoutResearchReportsMutualFundReportsRouteChildren,
  )

interface LayoutResearchReportsSpecialReportsRouteChildren {
  LayoutResearchReportsSpecialReportsAddRoute: typeof LayoutResearchReportsSpecialReportsAddRoute
}

const LayoutResearchReportsSpecialReportsRouteChildren: LayoutResearchReportsSpecialReportsRouteChildren =
  {
    LayoutResearchReportsSpecialReportsAddRoute:
      LayoutResearchReportsSpecialReportsAddRoute,
  }

const LayoutResearchReportsSpecialReportsRouteWithChildren =
  LayoutResearchReportsSpecialReportsRoute._addFileChildren(
    LayoutResearchReportsSpecialReportsRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutAddClientRoute: typeof LayoutAddClientRoute
  LayoutDownloadsRoute: typeof LayoutDownloadsRoute
  LayoutFundTransferRoute: typeof LayoutFundTransferRoute
  LayoutMarginUpdatesRoute: typeof LayoutMarginUpdatesRoute
  LayoutTestRoute: typeof LayoutTestRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutResearchReportsCommodityCurrencyReportsRoute: typeof LayoutResearchReportsCommodityCurrencyReportsRouteWithChildren
  LayoutResearchReportsDailyInsightsReportsRoute: typeof LayoutResearchReportsDailyInsightsReportsRouteWithChildren
  LayoutResearchReportsFundamentalReportsRoute: typeof LayoutResearchReportsFundamentalReportsRouteWithChildren
  LayoutResearchReportsMonthlyInsightsReportsRoute: typeof LayoutResearchReportsMonthlyInsightsReportsRouteWithChildren
  LayoutResearchReportsMutualFundReportsRoute: typeof LayoutResearchReportsMutualFundReportsRouteWithChildren
  LayoutResearchReportsSpecialReportsRoute: typeof LayoutResearchReportsSpecialReportsRouteWithChildren
  LayoutResearchReportsWeeklyInsightsReportsRoute: typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  LayoutResearchReportsWeeklyInsightReportsAddRoute: typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
  LayoutAcclAnnualReportsIndexRoute: typeof LayoutAcclAnnualReportsIndexRoute
  LayoutAcclFamiliarizationProgrammeIndexRoute: typeof LayoutAcclFamiliarizationProgrammeIndexRoute
  LayoutAcclInvestorRelationDocumentsIndexRoute: typeof LayoutAcclInvestorRelationDocumentsIndexRoute
  LayoutAcclPoliciesIndexRoute: typeof LayoutAcclPoliciesIndexRoute
  LayoutAcclAnnualReportsAddIndexRoute: typeof LayoutAcclAnnualReportsAddIndexRoute
  LayoutAcclFamiliarizationProgrammeAddIndexRoute: typeof LayoutAcclFamiliarizationProgrammeAddIndexRoute
  LayoutAcclInvestorRelationDocumentsAddIndexRoute: typeof LayoutAcclInvestorRelationDocumentsAddIndexRoute
  LayoutAcclPoliciesAddIndexRoute: typeof LayoutAcclPoliciesAddIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutAddClientRoute: LayoutAddClientRoute,
  LayoutDownloadsRoute: LayoutDownloadsRoute,
  LayoutFundTransferRoute: LayoutFundTransferRoute,
  LayoutMarginUpdatesRoute: LayoutMarginUpdatesRoute,
  LayoutTestRoute: LayoutTestRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutResearchReportsCommodityCurrencyReportsRoute:
    LayoutResearchReportsCommodityCurrencyReportsRouteWithChildren,
  LayoutResearchReportsDailyInsightsReportsRoute:
    LayoutResearchReportsDailyInsightsReportsRouteWithChildren,
  LayoutResearchReportsFundamentalReportsRoute:
    LayoutResearchReportsFundamentalReportsRouteWithChildren,
  LayoutResearchReportsMonthlyInsightsReportsRoute:
    LayoutResearchReportsMonthlyInsightsReportsRouteWithChildren,
  LayoutResearchReportsMutualFundReportsRoute:
    LayoutResearchReportsMutualFundReportsRouteWithChildren,
  LayoutResearchReportsSpecialReportsRoute:
    LayoutResearchReportsSpecialReportsRouteWithChildren,
  LayoutResearchReportsWeeklyInsightsReportsRoute:
    LayoutResearchReportsWeeklyInsightsReportsRoute,
  LayoutResearchReportsWeeklyInsightReportsAddRoute:
    LayoutResearchReportsWeeklyInsightReportsAddRoute,
  LayoutAcclAnnualReportsIndexRoute: LayoutAcclAnnualReportsIndexRoute,
  LayoutAcclFamiliarizationProgrammeIndexRoute:
    LayoutAcclFamiliarizationProgrammeIndexRoute,
  LayoutAcclInvestorRelationDocumentsIndexRoute:
    LayoutAcclInvestorRelationDocumentsIndexRoute,
  LayoutAcclPoliciesIndexRoute: LayoutAcclPoliciesIndexRoute,
  LayoutAcclAnnualReportsAddIndexRoute: LayoutAcclAnnualReportsAddIndexRoute,
  LayoutAcclFamiliarizationProgrammeAddIndexRoute:
    LayoutAcclFamiliarizationProgrammeAddIndexRoute,
  LayoutAcclInvestorRelationDocumentsAddIndexRoute:
    LayoutAcclInvestorRelationDocumentsAddIndexRoute,
  LayoutAcclPoliciesAddIndexRoute: LayoutAcclPoliciesAddIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof LayoutAboutRoute
  '/add-client': typeof LayoutAddClientRoute
  '/downloads': typeof LayoutDownloadsRoute
  '/fund-transfer': typeof LayoutFundTransferRoute
  '/margin-updates': typeof LayoutMarginUpdatesRoute
  '/test': typeof LayoutTestRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsRouteWithChildren
  '/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsRouteWithChildren
  '/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsRouteWithChildren
  '/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsRouteWithChildren
  '/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsRouteWithChildren
  '/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsRouteWithChildren
  '/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  '/research-reports/commodity-currency-reports/add': typeof LayoutResearchReportsCommodityCurrencyReportsAddRoute
  '/research-reports/daily-insights-reports/add': typeof LayoutResearchReportsDailyInsightsReportsAddRoute
  '/research-reports/fundamental-reports/add': typeof LayoutResearchReportsFundamentalReportsAddRoute
  '/research-reports/monthly-insights-reports/add': typeof LayoutResearchReportsMonthlyInsightsReportsAddRoute
  '/research-reports/mutual-fund-reports/add': typeof LayoutResearchReportsMutualFundReportsAddRoute
  '/research-reports/special-reports/add': typeof LayoutResearchReportsSpecialReportsAddRoute
  '/research-reports/weekly-insight-reports/add': typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
  '/accl/annual-reports': typeof LayoutAcclAnnualReportsIndexRoute
  '/accl/familiarization-programme': typeof LayoutAcclFamiliarizationProgrammeIndexRoute
  '/accl/investor-relation-documents': typeof LayoutAcclInvestorRelationDocumentsIndexRoute
  '/accl/policies': typeof LayoutAcclPoliciesIndexRoute
  '/accl/annual-reports/add': typeof LayoutAcclAnnualReportsAddIndexRoute
  '/accl/familiarization-programme/add': typeof LayoutAcclFamiliarizationProgrammeAddIndexRoute
  '/accl/investor-relation-documents/add': typeof LayoutAcclInvestorRelationDocumentsAddIndexRoute
  '/accl/policies/add': typeof LayoutAcclPoliciesAddIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof LayoutAboutRoute
  '/add-client': typeof LayoutAddClientRoute
  '/downloads': typeof LayoutDownloadsRoute
  '/fund-transfer': typeof LayoutFundTransferRoute
  '/margin-updates': typeof LayoutMarginUpdatesRoute
  '/test': typeof LayoutTestRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsRouteWithChildren
  '/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsRouteWithChildren
  '/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsRouteWithChildren
  '/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsRouteWithChildren
  '/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsRouteWithChildren
  '/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsRouteWithChildren
  '/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  '/research-reports/commodity-currency-reports/add': typeof LayoutResearchReportsCommodityCurrencyReportsAddRoute
  '/research-reports/daily-insights-reports/add': typeof LayoutResearchReportsDailyInsightsReportsAddRoute
  '/research-reports/fundamental-reports/add': typeof LayoutResearchReportsFundamentalReportsAddRoute
  '/research-reports/monthly-insights-reports/add': typeof LayoutResearchReportsMonthlyInsightsReportsAddRoute
  '/research-reports/mutual-fund-reports/add': typeof LayoutResearchReportsMutualFundReportsAddRoute
  '/research-reports/special-reports/add': typeof LayoutResearchReportsSpecialReportsAddRoute
  '/research-reports/weekly-insight-reports/add': typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
  '/accl/annual-reports': typeof LayoutAcclAnnualReportsIndexRoute
  '/accl/familiarization-programme': typeof LayoutAcclFamiliarizationProgrammeIndexRoute
  '/accl/investor-relation-documents': typeof LayoutAcclInvestorRelationDocumentsIndexRoute
  '/accl/policies': typeof LayoutAcclPoliciesIndexRoute
  '/accl/annual-reports/add': typeof LayoutAcclAnnualReportsAddIndexRoute
  '/accl/familiarization-programme/add': typeof LayoutAcclFamiliarizationProgrammeAddIndexRoute
  '/accl/investor-relation-documents/add': typeof LayoutAcclInvestorRelationDocumentsAddIndexRoute
  '/accl/policies/add': typeof LayoutAcclPoliciesAddIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/add-client': typeof LayoutAddClientRoute
  '/_layout/downloads': typeof LayoutDownloadsRoute
  '/_layout/fund-transfer': typeof LayoutFundTransferRoute
  '/_layout/margin-updates': typeof LayoutMarginUpdatesRoute
  '/_layout/test': typeof LayoutTestRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsRouteWithChildren
  '/_layout/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsRouteWithChildren
  '/_layout/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsRouteWithChildren
  '/_layout/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsRouteWithChildren
  '/_layout/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsRouteWithChildren
  '/_layout/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsRouteWithChildren
  '/_layout/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsRoute
  '/_layout/research-reports/commodity-currency-reports/add': typeof LayoutResearchReportsCommodityCurrencyReportsAddRoute
  '/_layout/research-reports/daily-insights-reports/add': typeof LayoutResearchReportsDailyInsightsReportsAddRoute
  '/_layout/research-reports/fundamental-reports/add': typeof LayoutResearchReportsFundamentalReportsAddRoute
  '/_layout/research-reports/monthly-insights-reports/add': typeof LayoutResearchReportsMonthlyInsightsReportsAddRoute
  '/_layout/research-reports/mutual-fund-reports/add': typeof LayoutResearchReportsMutualFundReportsAddRoute
  '/_layout/research-reports/special-reports/add': typeof LayoutResearchReportsSpecialReportsAddRoute
  '/_layout/research-reports/weekly-insight-reports/add': typeof LayoutResearchReportsWeeklyInsightReportsAddRoute
  '/_layout/accl/annual-reports/': typeof LayoutAcclAnnualReportsIndexRoute
  '/_layout/accl/familiarization-programme/': typeof LayoutAcclFamiliarizationProgrammeIndexRoute
  '/_layout/accl/investor-relation-documents/': typeof LayoutAcclInvestorRelationDocumentsIndexRoute
  '/_layout/accl/policies/': typeof LayoutAcclPoliciesIndexRoute
  '/_layout/accl/annual-reports/add/': typeof LayoutAcclAnnualReportsAddIndexRoute
  '/_layout/accl/familiarization-programme/add/': typeof LayoutAcclFamiliarizationProgrammeAddIndexRoute
  '/_layout/accl/investor-relation-documents/add/': typeof LayoutAcclInvestorRelationDocumentsAddIndexRoute
  '/_layout/accl/policies/add/': typeof LayoutAcclPoliciesAddIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/about'
    | '/add-client'
    | '/downloads'
    | '/fund-transfer'
    | '/margin-updates'
    | '/test'
    | '/users'
    | '/'
    | '/research-reports/commodity-currency-reports'
    | '/research-reports/daily-insights-reports'
    | '/research-reports/fundamental-reports'
    | '/research-reports/monthly-insights-reports'
    | '/research-reports/mutual-fund-reports'
    | '/research-reports/special-reports'
    | '/research-reports/weekly-insights-reports'
    | '/research-reports/commodity-currency-reports/add'
    | '/research-reports/daily-insights-reports/add'
    | '/research-reports/fundamental-reports/add'
    | '/research-reports/monthly-insights-reports/add'
    | '/research-reports/mutual-fund-reports/add'
    | '/research-reports/special-reports/add'
    | '/research-reports/weekly-insight-reports/add'
    | '/accl/annual-reports'
    | '/accl/familiarization-programme'
    | '/accl/investor-relation-documents'
    | '/accl/policies'
    | '/accl/annual-reports/add'
    | '/accl/familiarization-programme/add'
    | '/accl/investor-relation-documents/add'
    | '/accl/policies/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/add-client'
    | '/downloads'
    | '/fund-transfer'
    | '/margin-updates'
    | '/test'
    | '/users'
    | '/'
    | '/research-reports/commodity-currency-reports'
    | '/research-reports/daily-insights-reports'
    | '/research-reports/fundamental-reports'
    | '/research-reports/monthly-insights-reports'
    | '/research-reports/mutual-fund-reports'
    | '/research-reports/special-reports'
    | '/research-reports/weekly-insights-reports'
    | '/research-reports/commodity-currency-reports/add'
    | '/research-reports/daily-insights-reports/add'
    | '/research-reports/fundamental-reports/add'
    | '/research-reports/monthly-insights-reports/add'
    | '/research-reports/mutual-fund-reports/add'
    | '/research-reports/special-reports/add'
    | '/research-reports/weekly-insight-reports/add'
    | '/accl/annual-reports'
    | '/accl/familiarization-programme'
    | '/accl/investor-relation-documents'
    | '/accl/policies'
    | '/accl/annual-reports/add'
    | '/accl/familiarization-programme/add'
    | '/accl/investor-relation-documents/add'
    | '/accl/policies/add'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/about'
    | '/_layout/add-client'
    | '/_layout/downloads'
    | '/_layout/fund-transfer'
    | '/_layout/margin-updates'
    | '/_layout/test'
    | '/_layout/users'
    | '/_layout/'
    | '/_layout/research-reports/commodity-currency-reports'
    | '/_layout/research-reports/daily-insights-reports'
    | '/_layout/research-reports/fundamental-reports'
    | '/_layout/research-reports/monthly-insights-reports'
    | '/_layout/research-reports/mutual-fund-reports'
    | '/_layout/research-reports/special-reports'
    | '/_layout/research-reports/weekly-insights-reports'
    | '/_layout/research-reports/commodity-currency-reports/add'
    | '/_layout/research-reports/daily-insights-reports/add'
    | '/_layout/research-reports/fundamental-reports/add'
    | '/_layout/research-reports/monthly-insights-reports/add'
    | '/_layout/research-reports/mutual-fund-reports/add'
    | '/_layout/research-reports/special-reports/add'
    | '/_layout/research-reports/weekly-insight-reports/add'
    | '/_layout/accl/annual-reports/'
    | '/_layout/accl/familiarization-programme/'
    | '/_layout/accl/investor-relation-documents/'
    | '/_layout/accl/policies/'
    | '/_layout/accl/annual-reports/add/'
    | '/_layout/accl/familiarization-programme/add/'
    | '/_layout/accl/investor-relation-documents/add/'
    | '/_layout/accl/policies/add/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/add-client",
        "/_layout/downloads",
        "/_layout/fund-transfer",
        "/_layout/margin-updates",
        "/_layout/test",
        "/_layout/users",
        "/_layout/",
        "/_layout/research-reports/commodity-currency-reports",
        "/_layout/research-reports/daily-insights-reports",
        "/_layout/research-reports/fundamental-reports",
        "/_layout/research-reports/monthly-insights-reports",
        "/_layout/research-reports/mutual-fund-reports",
        "/_layout/research-reports/special-reports",
        "/_layout/research-reports/weekly-insights-reports",
        "/_layout/research-reports/weekly-insight-reports/add",
        "/_layout/accl/annual-reports/",
        "/_layout/accl/familiarization-programme/",
        "/_layout/accl/investor-relation-documents/",
        "/_layout/accl/policies/",
        "/_layout/accl/annual-reports/add/",
        "/_layout/accl/familiarization-programme/add/",
        "/_layout/accl/investor-relation-documents/add/",
        "/_layout/accl/policies/add/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/add-client": {
      "filePath": "_layout/add-client.tsx",
      "parent": "/_layout"
    },
    "/_layout/downloads": {
      "filePath": "_layout/downloads.tsx",
      "parent": "/_layout"
    },
    "/_layout/fund-transfer": {
      "filePath": "_layout/fund-transfer.tsx",
      "parent": "/_layout"
    },
    "/_layout/margin-updates": {
      "filePath": "_layout/margin-updates.tsx",
      "parent": "/_layout"
    },
    "/_layout/test": {
      "filePath": "_layout/test.tsx",
      "parent": "/_layout"
    },
    "/_layout/users": {
      "filePath": "_layout/users.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/commodity-currency-reports": {
      "filePath": "_layout/research-reports.commodity-currency-reports.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/research-reports/commodity-currency-reports/add"
      ]
    },
    "/_layout/research-reports/daily-insights-reports": {
      "filePath": "_layout/research-reports.daily-insights-reports.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/research-reports/daily-insights-reports/add"
      ]
    },
    "/_layout/research-reports/fundamental-reports": {
      "filePath": "_layout/research-reports.fundamental-reports.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/research-reports/fundamental-reports/add"
      ]
    },
    "/_layout/research-reports/monthly-insights-reports": {
      "filePath": "_layout/research-reports.monthly-insights-reports.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/research-reports/monthly-insights-reports/add"
      ]
    },
    "/_layout/research-reports/mutual-fund-reports": {
      "filePath": "_layout/research-reports.mutual-fund-reports.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/research-reports/mutual-fund-reports/add"
      ]
    },
    "/_layout/research-reports/special-reports": {
      "filePath": "_layout/research-reports.special-reports.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/research-reports/special-reports/add"
      ]
    },
    "/_layout/research-reports/weekly-insights-reports": {
      "filePath": "_layout/research-reports.weekly-insights-reports.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/commodity-currency-reports/add": {
      "filePath": "_layout/research-reports.commodity-currency-reports.add.tsx",
      "parent": "/_layout/research-reports/commodity-currency-reports"
    },
    "/_layout/research-reports/daily-insights-reports/add": {
      "filePath": "_layout/research-reports.daily-insights-reports.add.tsx",
      "parent": "/_layout/research-reports/daily-insights-reports"
    },
    "/_layout/research-reports/fundamental-reports/add": {
      "filePath": "_layout/research-reports.fundamental-reports.add.tsx",
      "parent": "/_layout/research-reports/fundamental-reports"
    },
    "/_layout/research-reports/monthly-insights-reports/add": {
      "filePath": "_layout/research-reports.monthly-insights-reports.add.tsx",
      "parent": "/_layout/research-reports/monthly-insights-reports"
    },
    "/_layout/research-reports/mutual-fund-reports/add": {
      "filePath": "_layout/research-reports.mutual-fund-reports.add.tsx",
      "parent": "/_layout/research-reports/mutual-fund-reports"
    },
    "/_layout/research-reports/special-reports/add": {
      "filePath": "_layout/research-reports.special-reports.add.tsx",
      "parent": "/_layout/research-reports/special-reports"
    },
    "/_layout/research-reports/weekly-insight-reports/add": {
      "filePath": "_layout/research-reports.weekly-insight-reports.add.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/annual-reports/": {
      "filePath": "_layout/accl/annual-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/familiarization-programme/": {
      "filePath": "_layout/accl/familiarization-programme/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/investor-relation-documents/": {
      "filePath": "_layout/accl/investor-relation-documents/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/policies/": {
      "filePath": "_layout/accl/policies/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/annual-reports/add/": {
      "filePath": "_layout/accl/annual-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/familiarization-programme/add/": {
      "filePath": "_layout/accl/familiarization-programme/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/investor-relation-documents/add/": {
      "filePath": "_layout/accl/investor-relation-documents/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/policies/add/": {
      "filePath": "_layout/accl/policies/add/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
